// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit 4b41cf3d71aa85cd4e75c96cbb54324481ee0b27).

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ClientUpdatesTable
    {
        [DataMember(Name = "ClientVersion")]
        public int ClientVersion;
        [DataMember(Name = "MinimumConnectionLevel")]
        public AuthorityLevel MinimumConnectionLevel;
        [DataMember(Name = "Reason")]
        public string Reason;

        public ClientUpdatesTable(
            int ClientVersion,
            AuthorityLevel MinimumConnectionLevel,
            string Reason
        )
        {
            this.ClientVersion = ClientVersion;
            this.MinimumConnectionLevel = MinimumConnectionLevel;
            this.Reason = Reason;
        }

        public ClientUpdatesTable()
        {
            this.Reason = "";
        }
    }
}
