// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit 4b41cf3d71aa85cd4e75c96cbb54324481ee0b27).

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Message
    {
        [DataMember(Name = "Sender")]
        public SpacetimeDB.Identity Sender;
        [DataMember(Name = "Sent")]
        public SpacetimeDB.Timestamp Sent;
        [DataMember(Name = "ChannelID")]
        public string ChannelId;
        [DataMember(Name = "Text")]
        public string Text;

        public Message(
            SpacetimeDB.Identity Sender,
            SpacetimeDB.Timestamp Sent,
            string ChannelId,
            string Text
        )
        {
            this.Sender = Sender;
            this.Sent = Sent;
            this.ChannelId = ChannelId;
            this.Text = Text;
        }

        public Message()
        {
            this.ChannelId = "";
            this.Text = "";
        }
    }
}
