// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit 4b41cf3d71aa85cd4e75c96cbb54324481ee0b27).

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class UserTable
    {
        [DataMember(Name = "Identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "Online")]
        public bool Online;
        [DataMember(Name = "AuthorityLevel")]
        public AuthorityLevel AuthorityLevel;
        [DataMember(Name = "Settings")]
        public UserSettings Settings;

        public UserTable(
            SpacetimeDB.Identity Identity,
            bool Online,
            AuthorityLevel AuthorityLevel,
            UserSettings Settings
        )
        {
            this.Identity = Identity;
            this.Online = Online;
            this.AuthorityLevel = AuthorityLevel;
            this.Settings = Settings;
        }

        public UserTable()
        {
            this.Settings = new();
        }
    }
}
