// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit 4b41cf3d71aa85cd4e75c96cbb54324481ee0b27).

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void CreateOrUpdateClientUpdateHandler(ReducerEventContext ctx, int version, string minimumConnectionLevel, string reason);
        public event CreateOrUpdateClientUpdateHandler? OnCreateOrUpdateClientUpdate;

        public void CreateOrUpdateClientUpdate(int version, string minimumConnectionLevel, string reason)
        {
            conn.InternalCallReducer(new Reducer.CreateOrUpdateClientUpdate(version, minimumConnectionLevel, reason), this.SetCallReducerFlags.CreateOrUpdateClientUpdateFlags);
        }

        public bool InvokeCreateOrUpdateClientUpdate(ReducerEventContext ctx, Reducer.CreateOrUpdateClientUpdate args)
        {
            if (OnCreateOrUpdateClientUpdate == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnCreateOrUpdateClientUpdate(
                ctx,
                args.Version,
                args.MinimumConnectionLevel,
                args.Reason
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class CreateOrUpdateClientUpdate : Reducer, IReducerArgs
        {
            [DataMember(Name = "version")]
            public int Version;
            [DataMember(Name = "minimumConnectionLevel")]
            public string MinimumConnectionLevel;
            [DataMember(Name = "reason")]
            public string Reason;

            public CreateOrUpdateClientUpdate(
                int Version,
                string MinimumConnectionLevel,
                string Reason
            )
            {
                this.Version = Version;
                this.MinimumConnectionLevel = MinimumConnectionLevel;
                this.Reason = Reason;
            }

            public CreateOrUpdateClientUpdate()
            {
                this.MinimumConnectionLevel = "";
                this.Reason = "";
            }

            string IReducerArgs.ReducerName => "CreateOrUpdateClientUpdate";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags CreateOrUpdateClientUpdateFlags;
        public void CreateOrUpdateClientUpdate(CallReducerFlags flags) => CreateOrUpdateClientUpdateFlags = flags;
    }
}
