// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit 4b41cf3d71aa85cd4e75c96cbb54324481ee0b27).

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void RegisterUserHandler(ReducerEventContext ctx, UserSettings settings);
        public event RegisterUserHandler? OnRegisterUser;

        public void RegisterUser(UserSettings settings)
        {
            conn.InternalCallReducer(new Reducer.RegisterUser(settings), this.SetCallReducerFlags.RegisterUserFlags);
        }

        public bool InvokeRegisterUser(ReducerEventContext ctx, Reducer.RegisterUser args)
        {
            if (OnRegisterUser == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnRegisterUser(
                ctx,
                args.Settings
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class RegisterUser : Reducer, IReducerArgs
        {
            [DataMember(Name = "settings")]
            public UserSettings Settings;

            public RegisterUser(UserSettings Settings)
            {
                this.Settings = Settings;
            }

            public RegisterUser()
            {
                this.Settings = new();
            }

            string IReducerArgs.ReducerName => "RegisterUser";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags RegisterUserFlags;
        public void RegisterUser(CallReducerFlags flags) => RegisterUserFlags = flags;
    }
}
