// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit 4b41cf3d71aa85cd4e75c96cbb54324481ee0b27).

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SetUserSettingsHandler(ReducerEventContext ctx, UserSettings settings);
        public event SetUserSettingsHandler? OnSetUserSettings;

        public void SetUserSettings(UserSettings settings)
        {
            conn.InternalCallReducer(new Reducer.SetUserSettings(settings), this.SetCallReducerFlags.SetUserSettingsFlags);
        }

        public bool InvokeSetUserSettings(ReducerEventContext ctx, Reducer.SetUserSettings args)
        {
            if (OnSetUserSettings == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSetUserSettings(
                ctx,
                args.Settings
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SetUserSettings : Reducer, IReducerArgs
        {
            [DataMember(Name = "settings")]
            public UserSettings Settings;

            public SetUserSettings(UserSettings Settings)
            {
                this.Settings = Settings;
            }

            public SetUserSettings()
            {
                this.Settings = new();
            }

            string IReducerArgs.ReducerName => "SetUserSettings";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags SetUserSettingsFlags;
        public void SetUserSettings(CallReducerFlags flags) => SetUserSettingsFlags = flags;
    }
}
