// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit 4b41cf3d71aa85cd4e75c96cbb54324481ee0b27).

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UpdateUserAuthorityHandler(ReducerEventContext ctx, AuthorityLevel level, SpacetimeDB.Identity identityToUpdate);
        public event UpdateUserAuthorityHandler? OnUpdateUserAuthority;

        public void UpdateUserAuthority(AuthorityLevel level, SpacetimeDB.Identity identityToUpdate)
        {
            conn.InternalCallReducer(new Reducer.UpdateUserAuthority(level, identityToUpdate), this.SetCallReducerFlags.UpdateUserAuthorityFlags);
        }

        public bool InvokeUpdateUserAuthority(ReducerEventContext ctx, Reducer.UpdateUserAuthority args)
        {
            if (OnUpdateUserAuthority == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnUpdateUserAuthority(
                ctx,
                args.Level,
                args.IdentityToUpdate
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UpdateUserAuthority : Reducer, IReducerArgs
        {
            [DataMember(Name = "level")]
            public AuthorityLevel Level;
            [DataMember(Name = "identityToUpdate")]
            public SpacetimeDB.Identity IdentityToUpdate;

            public UpdateUserAuthority(
                AuthorityLevel Level,
                SpacetimeDB.Identity IdentityToUpdate
            )
            {
                this.Level = Level;
                this.IdentityToUpdate = IdentityToUpdate;
            }

            public UpdateUserAuthority()
            {
            }

            string IReducerArgs.ReducerName => "UpdateUserAuthority";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags UpdateUserAuthorityFlags;
        public void UpdateUserAuthority(CallReducerFlags flags) => UpdateUserAuthorityFlags = flags;
    }
}
