// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit 4b41cf3d71aa85cd4e75c96cbb54324481ee0b27).

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UpdateMessageHandler(ReducerEventContext ctx, MessageData data);
        public event UpdateMessageHandler? OnUpdateMessage;

        public void UpdateMessage(MessageData data)
        {
            conn.InternalCallReducer(new Reducer.UpdateMessage(data), this.SetCallReducerFlags.UpdateMessageFlags);
        }

        public bool InvokeUpdateMessage(ReducerEventContext ctx, Reducer.UpdateMessage args)
        {
            if (OnUpdateMessage == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnUpdateMessage(
                ctx,
                args.Data
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UpdateMessage : Reducer, IReducerArgs
        {
            [DataMember(Name = "data")]
            public MessageData Data;

            public UpdateMessage(MessageData Data)
            {
                this.Data = Data;
            }

            public UpdateMessage()
            {
                this.Data = new();
            }

            string IReducerArgs.ReducerName => "UpdateMessage";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags UpdateMessageFlags;
        public void UpdateMessage(CallReducerFlags flags) => UpdateMessageFlags = flags;
    }
}
