// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit 4b41cf3d71aa85cd4e75c96cbb54324481ee0b27).

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UpdateUserAuthorityDashboardHandler(ReducerEventContext ctx, string level, string identityHex);
        public event UpdateUserAuthorityDashboardHandler? OnUpdateUserAuthorityDashboard;

        public void UpdateUserAuthorityDashboard(string level, string identityHex)
        {
            conn.InternalCallReducer(new Reducer.UpdateUserAuthorityDashboard(level, identityHex), this.SetCallReducerFlags.UpdateUserAuthorityDashboardFlags);
        }

        public bool InvokeUpdateUserAuthorityDashboard(ReducerEventContext ctx, Reducer.UpdateUserAuthorityDashboard args)
        {
            if (OnUpdateUserAuthorityDashboard == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnUpdateUserAuthorityDashboard(
                ctx,
                args.Level,
                args.IdentityHex
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UpdateUserAuthorityDashboard : Reducer, IReducerArgs
        {
            [DataMember(Name = "level")]
            public string Level;
            [DataMember(Name = "identityHex")]
            public string IdentityHex;

            public UpdateUserAuthorityDashboard(
                string Level,
                string IdentityHex
            )
            {
                this.Level = Level;
                this.IdentityHex = IdentityHex;
            }

            public UpdateUserAuthorityDashboard()
            {
                this.Level = "";
                this.IdentityHex = "";
            }

            string IReducerArgs.ReducerName => "UpdateUserAuthorityDashboard";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags UpdateUserAuthorityDashboardFlags;
        public void UpdateUserAuthorityDashboard(CallReducerFlags flags) => UpdateUserAuthorityDashboardFlags = flags;
    }
}
