// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit 4b41cf3d71aa85cd4e75c96cbb54324481ee0b27).

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UpdateClientRulesHandler(ReducerEventContext ctx, int version, string isClientAllowedToConnect);
        public event UpdateClientRulesHandler? OnUpdateClientRules;

        public void UpdateClientRules(int version, string isClientAllowedToConnect)
        {
            conn.InternalCallReducer(new Reducer.UpdateClientRules(version, isClientAllowedToConnect), this.SetCallReducerFlags.UpdateClientRulesFlags);
        }

        public bool InvokeUpdateClientRules(ReducerEventContext ctx, Reducer.UpdateClientRules args)
        {
            if (OnUpdateClientRules == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnUpdateClientRules(
                ctx,
                args.Version,
                args.IsClientAllowedToConnect
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UpdateClientRules : Reducer, IReducerArgs
        {
            [DataMember(Name = "version")]
            public int Version;
            [DataMember(Name = "isClientAllowedToConnect")]
            public string IsClientAllowedToConnect;

            public UpdateClientRules(
                int Version,
                string IsClientAllowedToConnect
            )
            {
                this.Version = Version;
                this.IsClientAllowedToConnect = IsClientAllowedToConnect;
            }

            public UpdateClientRules()
            {
                this.IsClientAllowedToConnect = "";
            }

            string IReducerArgs.ReducerName => "UpdateClientRules";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags UpdateClientRulesFlags;
        public void UpdateClientRules(CallReducerFlags flags) => UpdateClientRulesFlags = flags;
    }
}
