// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit 4b41cf3d71aa85cd4e75c96cbb54324481ee0b27).

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ClientUpdatesHandle : RemoteTableHandle<EventContext, ClientUpdatesTable>
        {
            protected override string RemoteTableName => "ClientUpdates";

            public sealed class ClientVersionUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(ClientUpdatesTable row) => row.ClientVersion;

                public ClientVersionUniqueIndex(ClientUpdatesHandle table) : base(table) { }
            }

            public readonly ClientVersionUniqueIndex ClientVersion;

            internal ClientUpdatesHandle(DbConnection conn) : base(conn)
            {
                ClientVersion = new(this);
            }

            protected override object GetPrimaryKey(ClientUpdatesTable row) => row.ClientVersion;
        }

        public readonly ClientUpdatesHandle ClientUpdates;
    }
}
