// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit 4b41cf3d71aa85cd4e75c96cbb54324481ee0b27).

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ClientRulesHandle : RemoteTableHandle<EventContext, ClientRulesTable>
        {
            protected override string RemoteTableName => "ClientRules";

            public sealed class IdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(ClientRulesTable row) => row.Id;

                public IdUniqueIndex(ClientRulesHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal ClientRulesHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(ClientRulesTable row) => row.Id;
        }

        public readonly ClientRulesHandle ClientRules;
    }
}
