// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit 4b41cf3d71aa85cd4e75c96cbb54324481ee0b27).

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class MessageHandle : RemoteTableHandle<EventContext, MessageTable>
        {
            protected override string RemoteTableName => "Message";

            public sealed class MessageIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(MessageTable row) => row.MessageId;

                public MessageIdUniqueIndex(MessageHandle table) : base(table) { }
            }

            public readonly MessageIdUniqueIndex MessageId;

            internal MessageHandle(DbConnection conn) : base(conn)
            {
                MessageId = new(this);
            }

            protected override object GetPrimaryKey(MessageTable row) => row.MessageId;
        }

        public readonly MessageHandle Message;
    }
}
